export const CHANGE_FORM_FIELD = 'CHANGE_FORM_FIELD';
export const REMOVE_SERVISE = 'REMOVE_SERVISE';
export const ADD_SERVISE = 'ADD_SERVISE';
export const EDIT_SERVISE = 'EDIT_SERVISE';
export const FILTER_SERVISE = 'FILTER_SERVISE';
export const GET_SERVISE = 'GET_SERVISE';
export const CHANGE_FILTER_FIELD = 'CHANGE_FILTER_FIELD';